apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    name: spark-master
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        name: spark-master
    spec:
      containers:
      - image: docker-registry.default.svc:5000/spark-openshift/spark:2.4.2
        name: spark-master
        args:
          - 'master'
        ports:
          - name: spark-master
            containerPort: 7077
            protocol: TCP
          - name: master-ui
            containerPort: 8080
            protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources: {}
  restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - spark-master
      from:
        kind: ImageStreamTag
        name: spark:2.4.2
    type: ImageChange
