apiVersion: v1
kind: Service
metadata:
  name: spark-master-ui
  labels:
    name: spark-master-ui
spec:
  ports:
  - name: master-ui
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: spark-master
