apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    name: spark-master
spec:
  ports:
  - name: spark-master
    port: 7077
    protocol: TCP
    nodePort: 30077
    targetPort: 7077
  type: NodePort
  selector:
    name: spark-master
